global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: app
    static_configs:
      - targets:
          - app:5173

  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090
